ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.ttfeed.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/ttfeed"
    user = "ttfeed"
    password = "ttfeed"
    driver = "org.postgresql.Driver"
}